site_name: CIS Hardened Images

nav:
    - Home: index.md
    - GENERAL:
        - 'About CIS Hardened Images': source/About CIS-Hosted CSAT.md

    - Configuration Guide:
        - 'Creating CSAT Account for the first time': source/Creating CSAT Account.md
        - 'Joining an existing account': source/Joining an existing account.md
        - 'Requirements': source/Requirements.md
        
    - Users and Organization:
        - 'Organization Creation': source/Organization Creation.md
        - 'Primary Owner': source/Primary Owner.md
        - 'Users': source/Users.md

        
theme:
    name: readthedocs
